<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="opsInterface"
     targetNamespace="http://soahost.co.ke/SOATutorial/OrderProcessingSystem/opsInterface"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://soahost.co.ke/SOATutorial/OrderProcessingSystem/opsInterface"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="opsSOAPService">
        <plnk:role name="opsCallbackAsyncPortType" portType="tns:opsCallbackAsyncPortType"/>
        <plnk:role name="opsRequestAsyncPortType" portType="tns:opsRequestAsyncPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://soahost.co.ke/SOATutorial/OrderProcessingSystem/opsInterface"
         location="opsInterface.wsdl"/>
</wsdl:definitions>
