<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="bmsInterface"
     targetNamespace="http://soahost.co.ke/SOATutorial/BillingManagementSystem/bmsInterface"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:bpws="http://docs.oasis-open.org/wsbpel/2.0/process/executable"
     xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype"
     xmlns:tns="http://soahost.co.ke/SOATutorial/BillingManagementSystem/bmsInterface"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <plnk:partnerLinkType name="bmsSOAPService">
        <plnk:role name="bmsRequestAsyncPortType" portType="tns:bmsRequestAsyncPortType"/>
        <plnk:role name="bmsCallbackAsyncPortType" portType="tns:bmsCallbackAsyncPortType"/>
    </plnk:partnerLinkType>
    <wsdl:import namespace="http://soahost.co.ke/SOATutorial/BillingManagementSystem/bmsInterface"
         location="bmsInterface.wsdl"/>
</wsdl:definitions>
